site_name: Regis
site_url: &SITE_URL https://soymadip.github.io/Regis

repo_url: &REPO_URL https://github.com/soymadip/Regis
repo_name: soymadip/Regis
edit_uri: edit/main/docs/docs

nav:
  - index.md 
  - deploy.md 
  - commands.md
  - credits.md

extra:
  generator: false

extra_css:
  - src/custom.css

plugins:
  - social
  - search
  - tags

theme:
  name: material
  palette:
    scheme: default
    primary: deep orange 
    accent: orange
  # custom_dir: overrides

  icon:
    repo: fontawesome/brands/github

  logo: &LOGO_ICON src/icon.png
  favicon: *LOGO_ICON

  features:
    - header.autohide
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.purne
    - navigation.indexes
    - navigation.footer 
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - tables
  - def_list
  - footnotes
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: false 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
